### ISSUE TITLE
pylutron seem to just go away

### ISSUE THREAD

**Issue by avpavp** [thecynic/pylutron#32]
I have a big lutron install, prob 100+ devices.  Using Home Assistant.  It's a big install, shared with a Crestron system.

It seems after random periods of time (hours or days), the pylutron thread just seems to stop or go away.  I suspected some other exception was being thrown (and not handled) in the main run fn.  So I added more generic exception handling there, and sprinkled in some more logging to try and determine where/how it was failing.

Unfortunately, I'm not seeing anything revealing.  I see lots of logging, but ultimately it calls a (blocking) read (as is normal) and that's the last log msg I ever see.

I see there are some outstanding PRs here, and I'm not sure about the lutron firmware version...

Any ideas or suggestions as to where to log next or how else to try and track down this issue?

Thanks!

**Comment by avpavp** [comment]
So I think I've finally gotten to the bottom of this.  In the Button class, line 702 (__init__.py):

`if action not in ev_map:`

Throws an exception - anyone got any idea why this would be happening?

**Comment by thecynic** [comment]
Do you have a full stack trace?

**Comment by thecynic** [comment]
I highly doubt the actual issues in the map lookup, it'd be weird but stranger things have happen.

I think the bigger issue is the stuck in read. telnetlib is blocking by default, so if the connection dies (either because you have network issues or main repeater goes away) we'd recover after whatever linux decides is appropriate. Take a look at https://github.com/thecynic/pylutron/pull/34 . It should handle the disconnects better.

I think there's more work to do there, but it's better than what we have today.

**Comment by thecynic** [comment]
I believe #34 should resolve most connection issues. Closing this issue. Please open a new issue if things get broken in a new way.
